### ISSUE TITLE
Can't locate object method "search" via package "Mojo::Loader"

### ISSUE THREAD

**Issue by senorsmile** [koorchik/FastNotes-Proto#3]
Getting this error using the newest Mojolicious: v6.37.

**Comment by senorsmile** [comment]
I was able to get it up and going with Carton and the following cpanfile:

`
requires 'Mojolicious', '<= 4.99';
requires 'DBD::SQLite', '<= 1.46';
requires 'DBIx::Simple';
`

I tried modifying the code to work with Mojolicious 6.37, but the differences seem to be too numerous, and my familiarity with Mojolicious much too new.

**Comment by koorchik** [comment]
Thanks. Now I have lack of time but I will try to fix it

**Comment by koorchik** [comment]
Fixed.
