### ISSUE TITLE
Mojo Upload

### ISSUE THREAD

**Issue by vijaybose18** [koorchik/FastNotes-Proto#5]
Hi All,

I tried to read CSV file data in server using Mojo Upload package. But I faced field split issue. Then I tried to implement Text::CSV but I can't read file handle from Mojo Upload.

Can any one help me to resolve my problem.

Thanks,
Vijay

**Comment by koorchik** [comment]
How is it related to this Proto? I've checked project's deps,  there is no dependency on Text::CSV

**Comment by koorchik** [comment]
Fixed
