### ISSUE TITLE
Could you make this project conform to your perlcon 2019 talk?

### ISSUE THREAD

**Issue by aero** [koorchik/FastNotes-Proto#6]
Hi,
I've read your perlcon 2019 talk( The working architecture of Perl applications: https://perlcon.eu/talk/69 ).

I searched your github repository for fully working example for that architecure and found this project.
but I seems that this does not follow the architecture in your talk.

 Could you make this project conform to your perlcon 2019 talk?

**Comment by koorchik** [comment]
I am not sure that I will find time for it. But I am going to open source NodeJs version of our boilerplate. It is very similar to Perl structure

**Comment by koorchik** [comment]
By the way here is an example of telegram chatbot in Perl 6 built on top of this architecture  - https://github.com/koorchik/codegolf-telegram-bot

I've just started with this, but possibly it will be useful for you as example)
